import { Heading } from "@/shared/components/Heading";
import { Presentation } from "@/shared/components/Presentation";
import Head from "next/head";

const collection = [
  "salmon",
  "population",
  "psychology",
  "red",
  "mole",
  "embrace",
  "consultation",
  "absence",
];

export default function Page() {
  return (
    <>
      <Head>
        <title>Direction | Layout</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Heading>DIRECTION</Heading>
        <Presentation
          heading="Default behaviour."
          tw=""
          collection={collection}
        />
        <hr />
        <Presentation
          heading="display: flex"
          tw="flex"
          collection={collection}
        />
        <Presentation
          heading="display: grid"
          tw="grid"
          collection={collection}
        />
        <hr />
        <Presentation
          heading="display: flex, flex-direction: column"
          tw="flex flex-col"
          collection={collection}
        />
        <Presentation
          heading="display: grid, grid-auto-flow: column"
          tw="grid grid-flow-col"
          collection={collection}
        />
      </>
    </>
  );
}
