import { Heading } from "@/shared/components/Heading";
import { tailwindClasses } from "@/shared/utils/tailwindClasses";
import Head from "next/head";

const collection = ["HOME", "DOCS", "ABOUT", "CONTACT"];
const placeholder = new Array(3).fill(" ");

export default function Page() {
  return (
    <>
      <Head>
        <title>Implementation | Layout</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Heading>IMPLEMENTATION</Heading>
        <h2>display: flex + margin-left: auto</h2>
        <nav className="p-4 outline outline-blue-500">
          <ul className="flex gap-2">
            {collection.map((link, i) => {
              return (
                <li
                  className={tailwindClasses(i === 1 ? "ml-auto" : "")}
                  key={`link-${i}`}
                >
                  <a
                    className={tailwindClasses(
                      i > 0 ? "rounded bg-blue-200 p-2 text-blue-500" : ""
                    )}
                    href="#"
                  >
                    {link}
                  </a>
                </li>
              );
            })}
          </ul>
        </nav>
        <h2>
          display: grid, grid-auto-flow: column, grid-template-columns: 1fr
        </h2>
        <nav className="p-4 outline outline-blue-500">
          <ul className="grid grid-flow-col grid-cols-1 gap-2">
            {collection.map((link, i) => {
              return (
                <li key={`link-${i}`}>
                  <a
                    className={tailwindClasses(
                      i > 0 ? "rounded bg-blue-200 p-2 text-blue-500" : ""
                    )}
                    href="#"
                  >
                    {link}
                  </a>
                </li>
              );
            })}
          </ul>
        </nav>
        <hr />
        <h2>display: flex + flex: 1 1 0%</h2>
        <section className="flex flex-wrap gap-4">
          {placeholder.map((_, i) => {
            return (
              <div
                className="flex flex-shrink flex-grow basis-[12.5rem] flex-col gap-4 rounded bg-blue-200 p-4"
                key={`card-${i}`}
              >
                <div className="aspect-square rounded bg-white"></div>
                <h4>Title</h4>
                <button className="rounded bg-blue-500 py-2 text-white">
                  DETAILS
                </button>
              </div>
            );
          })}
        </section>
        <h2>
          display: grid, grid-template-columns: repeat(auto-fit, minmax(12.5rem,
          1fr))
        </h2>
        <section className="grid grid-cols-[repeat(auto-fit,_minmax(12.5rem,_1fr))] gap-4">
          {placeholder.map((_, i) => {
            return (
              <div
                className="flex flex-col gap-4 rounded bg-blue-200 p-4"
                key={`card-${i}`}
              >
                <div className="aspect-square rounded bg-white"></div>
                <h4>Title</h4>
                <button className="rounded bg-blue-500 py-2 text-white">
                  DETAILS
                </button>
              </div>
            );
          })}
        </section>
      </>
    </>
  );
}
