import Head from "next/head";
import { ReactNode } from "react";
import Image from "next/image";
import { Heading } from "@/shared/components/Heading";
import { Bold } from "@/shared/components/Bold";
import { tailwindClasses } from "@/shared/utils/tailwindClasses";
import { prefix } from "@/shared/utils/prefix";

const collection = new Array(8).fill("");

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Layout</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Heading>LAYOUT</Heading>
        <Container />
        <Cards />
      </>
    </>
  );
}

function Container() {
  return (
    <>
      <p className="mx-auto max-w-2xl text-center text-[clamp(1rem,_5vw,_2rem)]">
        Responsive layout with <Bold>Flexbox</Bold>, <Bold>CSS Grid</Bold>,{" "}
        <Bold>Media queries</Bold>, <Bold>Container queries</Bold> & many more!
      </p>
      <MagicCard />
    </>
  );
}

function MagicCard() {
  return (
    <>
      <section className="@container">
        <div
          className={tailwindClasses(
            "grid grid-cols-1 grid-rows-[1fr_0.5fr] p-4 text-neutral-100",
            prefix("@sm", "grid-cols-4 grid-rows-1 rounded bg-neutral-800"),
            prefix(
              "@lg",
              "grid-cols-8 grid-rows-[repeat(6,_50px)] bg-transparent"
            ),
            prefix("@4xl", "grid-cols-12 grid-rows-[repeat(6,_50px)]")
          )}
        >
          <Image
            className={tailwindClasses(
              "w-full rounded rounded-b-none",
              prefix("@sm", "col-span-1"),
              prefix("@lg", "col-span-2 col-start-3 row-start-1 rounded")
            )}
            src="https://source.unsplash.com/random/500x500?nature"
            alt="Random image"
            priority={true}
            width={500}
            height={500}
          />
          <div
            className={tailwindClasses(
              "flex items-center justify-center rounded rounded-t-none bg-neutral-800 p-4 text-3xl font-bold",
              prefix("@sm", "col-span-3"),
              prefix(
                "@lg",
                "col-span-4 col-start-4 row-span-4 row-start-3 rounded"
              ),
              prefix("@4xl", "col-span-8 col-start-4 row-span-4 row-start-3")
            )}
          >
            <p>Magic card!</p>
          </div>
        </div>
      </section>
    </>
  );
}

function Cards() {
  return (
    <>
      <div className="grid grid-cols-[repeat(auto-fit,_minmax(min(12.5rem,_100%),_1fr))] gap-4">
        {collection.map((e, i) => {
          return (
            <div
              className="flex flex-col gap-4 rounded border bg-white p-4"
              key={`card-${i}`}
            >
              <Image
                className="aspect-square w-full rounded"
                src="https://source.unsplash.com/random/500x500?nature"
                alt="Random image"
                priority={true}
                width={500}
                height={500}
              />
              <h3 className="font-bold">Title of the card</h3>
              <button className="w-full rounded bg-neutral-200 p-2 text-center text-lg font-semibold text-neutral-500">
                Details
              </button>
            </div>
          );
        })}
      </div>
    </>
  );
}
